### ISSUE TITLE
Add index variable generated by Collection

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#3465]
As a user I want to be able to apply styles and properties depending on the index of the iteration

**Comment by kof** [comment]
Workarounds for now:

1. css embed with

```css
:last-child {
  display: nonel
}
```
2. use the specific id or name inside the item to determine its the last one
