### ISSUE TITLE
UI for combinations of "states" (pseudo-classes) and link current-page state

### ISSUE THREAD

**Issue by paulrudy** [webstudio-is/webstudio#4094]
If it wouldn't overcomplicate the UI, I'd like to be able to style combinations like "hover + visited", or "hover+ current page". In CSS, we can do:

```css
a {
  color: red;
  text-decoration: none;
  
  &:hover {
    text-decoration: underline;
    color: blue;

    &.current-page {
      text-decoration: initial;
      color: initial;
    }
            
    &:visited {
      color: initial;
    }
  }
}
```

where `.current-page` would be equivalent to the Webstudio "Current Page" state for links.

Perhaps a multi-select option in the dropdown for selecting states?

**Comment by kof** [comment]
The same would be with "Current Page" state on a link:

```css
a[aria-current=page] {
    color: blue;
    --icon-display: block;      
}
.child {
   display: var(--icon-display, none)
}
```
