### ISSUE TITLE
Style conditions and variants

### ISSUE THREAD

**Issue by kof** [webstudio-is/webstudio#4249]
As a builder I want to be able to change styling of an element depending on some external value. That value can also be used as a way to switch variants.

I see variants as a form of state-dependent styling. Variants are just predefined states. State value allows to choose the active variant.

## CSS Next

In the future versions of CSS with container queries, CSS rules can be switched via a single CSS variable. In this case --variant switches an entire CSS rule or multiple rules.

```css
@container style(--variant: destructive) {
  .button {
    background-color: red;
  }
}

@container style(--button-display: block) {
  .button {
    display: block;
  }
}


style(--variant: destructive | ghost) -> variant = ['destructive', 'ghost']
```

While we can't generate this CSS yet, it will take years to get adoption, the mental model should be this:

A condition wraps both: Style Rules and Media Queries and allows user to switch them using CSS variable. CSS Variable value can be statically predefined or switched out dynamically during runtime. The value of the variable can represent a named variant as well as specific values. Builder should be able to structure conditions the way they need it
