### ISSUE TITLE
Title: Normalize Safari iOS User Agent Styles to Match Chrome Defaults

### ISSUE THREAD

**Issue by istarkov** [webstudio-is/webstudio#4884]
## Description  
On a regular basis, we encounter issues with iOS-rendered sites due to the WebKit user agent stylesheet, particularly the section related to button styles:  

🔗 **Relevant Code:**  
[WebKit `html.css` Line 909-919](https://github.com/WebKit/WebKit/blob/6dcf1e7e2a9f26587ec853af1ecd37b94583fa26/Source/WebCore/css/html.css#L909C5-L919)  

```css
#if defined(WTF_PLATFORM_IOS_FAMILY) && WTF_PLATFORM_IOS_FAMILY

input[type="submit"], input[type="submit"]:active,
button[type="submit"], button[type="submit"]:active,
button[type="menu"], button[type="menu"]:active {
    background-color: -apple-system-blue;
    color: white;
    font-weight: bold;
}

#endif
```

This leads to inconsistencies in styling across browsers, as Safari iOS applies different button colors and font weights compared to other browsers like Chrome.  

## ✅ Proposed Solution  
To ensure a consistent cross-browser experience, we should normalize all cases where `defined(WTF_PLATFORM_IOS_FAMILY) && WTF_PLATFORM_IOS_FAMILY` is used by aligning them with Chrome's defaults.
